/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated/strategies'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedShadowRouteImport } from './routes/_authenticated/shadow'
import { Route as AuthenticatedReadinessRouteImport } from './routes/_authenticated/readiness'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedOptimizerRouteImport } from './routes/_authenticated/optimizer'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedMobileRouteImport } from './routes/_authenticated/mobile'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedIntelRouteImport } from './routes/_authenticated/intel'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedCapitalRouteImport } from './routes/_authenticated/capital'
import { Route as AuthenticatedAutonomousRouteImport } from './routes/_authenticated/autonomous'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAltdataRouteImport } from './routes/_authenticated/altdata'
import { Route as AuthenticatedAccuracyRouteImport } from './routes/_authenticated/accuracy'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedBacktestsIdRouteImport } from './routes/_authenticated/backtests.$id'
import { Route as AuthenticatedAccountsNewRouteImport } from './routes/_authenticated/accounts.new'
import { Route as ApiPublicCronAutonomousRouteImport } from './routes/api/public/cron.autonomous'
import { Route as AuthenticatedAccountsIdActivateRouteImport } from './routes/_authenticated/accounts.$id.activate'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShadowRoute = AuthenticatedShadowRouteImport.update({
  id: '/shadow',
  path: '/shadow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReadinessRoute = AuthenticatedReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptimizerRoute = AuthenticatedOptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMobileRoute = AuthenticatedMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelRoute = AuthenticatedIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCapitalRoute = AuthenticatedCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutonomousRoute = AuthenticatedAutonomousRouteImport.update({
  id: '/autonomous',
  path: '/autonomous',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAltdataRoute = AuthenticatedAltdataRouteImport.update({
  id: '/altdata',
  path: '/altdata',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccuracyRoute = AuthenticatedAccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacktestsIdRoute =
  AuthenticatedBacktestsIdRouteImport.update({
    id: '/backtests/$id',
    path: '/backtests/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsNewRoute =
  AuthenticatedAccountsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)
const ApiPublicCronAutonomousRoute = ApiPublicCronAutonomousRouteImport.update({
  id: '/api/public/cron/autonomous',
  path: '/api/public/cron/autonomous',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsIdActivateRoute =
  AuthenticatedAccountsIdActivateRouteImport.update({
    id: '/$id/activate',
    path: '/$id/activate',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/accuracy': typeof AuthenticatedAccuracyRoute
  '/altdata': typeof AuthenticatedAltdataRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/autonomous': typeof AuthenticatedAutonomousRoute
  '/capital': typeof AuthenticatedCapitalRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/intel': typeof AuthenticatedIntelRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/lab': typeof AuthenticatedLabRoute
  '/market': typeof AuthenticatedMarketRoute
  '/mobile': typeof AuthenticatedMobileRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/optimizer': typeof AuthenticatedOptimizerRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/shadow': typeof AuthenticatedShadowRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/backtests/$id': typeof AuthenticatedBacktestsIdRoute
  '/accounts/$id/activate': typeof AuthenticatedAccountsIdActivateRoute
  '/api/public/cron/autonomous': typeof ApiPublicCronAutonomousRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/accuracy': typeof AuthenticatedAccuracyRoute
  '/altdata': typeof AuthenticatedAltdataRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/autonomous': typeof AuthenticatedAutonomousRoute
  '/capital': typeof AuthenticatedCapitalRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/intel': typeof AuthenticatedIntelRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/lab': typeof AuthenticatedLabRoute
  '/market': typeof AuthenticatedMarketRoute
  '/mobile': typeof AuthenticatedMobileRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/optimizer': typeof AuthenticatedOptimizerRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/readiness': typeof AuthenticatedReadinessRoute
  '/shadow': typeof AuthenticatedShadowRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/backtests/$id': typeof AuthenticatedBacktestsIdRoute
  '/accounts/$id/activate': typeof AuthenticatedAccountsIdActivateRoute
  '/api/public/cron/autonomous': typeof ApiPublicCronAutonomousRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/_authenticated/accuracy': typeof AuthenticatedAccuracyRoute
  '/_authenticated/altdata': typeof AuthenticatedAltdataRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/autonomous': typeof AuthenticatedAutonomousRoute
  '/_authenticated/capital': typeof AuthenticatedCapitalRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/intel': typeof AuthenticatedIntelRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/mobile': typeof AuthenticatedMobileRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/optimizer': typeof AuthenticatedOptimizerRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/readiness': typeof AuthenticatedReadinessRoute
  '/_authenticated/shadow': typeof AuthenticatedShadowRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/_authenticated/accounts/new': typeof AuthenticatedAccountsNewRoute
  '/_authenticated/backtests/$id': typeof AuthenticatedBacktestsIdRoute
  '/_authenticated/accounts/$id/activate': typeof AuthenticatedAccountsIdActivateRoute
  '/api/public/cron/autonomous': typeof ApiPublicCronAutonomousRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/accounts'
    | '/accuracy'
    | '/altdata'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/autonomous'
    | '/capital'
    | '/compliance'
    | '/dashboard'
    | '/history'
    | '/intel'
    | '/intelligence'
    | '/journal'
    | '/lab'
    | '/market'
    | '/mobile'
    | '/monitoring'
    | '/notifications'
    | '/onboarding'
    | '/optimizer'
    | '/performance'
    | '/portfolio'
    | '/positions'
    | '/readiness'
    | '/shadow'
    | '/signals'
    | '/strategies'
    | '/accounts/new'
    | '/backtests/$id'
    | '/accounts/$id/activate'
    | '/api/public/cron/autonomous'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/accounts'
    | '/accuracy'
    | '/altdata'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/autonomous'
    | '/capital'
    | '/compliance'
    | '/dashboard'
    | '/history'
    | '/intel'
    | '/intelligence'
    | '/journal'
    | '/lab'
    | '/market'
    | '/mobile'
    | '/monitoring'
    | '/notifications'
    | '/onboarding'
    | '/optimizer'
    | '/performance'
    | '/portfolio'
    | '/positions'
    | '/readiness'
    | '/shadow'
    | '/signals'
    | '/strategies'
    | '/accounts/new'
    | '/backtests/$id'
    | '/accounts/$id/activate'
    | '/api/public/cron/autonomous'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/accounts'
    | '/_authenticated/accuracy'
    | '/_authenticated/altdata'
    | '/_authenticated/analytics'
    | '/_authenticated/approvals'
    | '/_authenticated/automation'
    | '/_authenticated/autonomous'
    | '/_authenticated/capital'
    | '/_authenticated/compliance'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/intel'
    | '/_authenticated/intelligence'
    | '/_authenticated/journal'
    | '/_authenticated/lab'
    | '/_authenticated/market'
    | '/_authenticated/mobile'
    | '/_authenticated/monitoring'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/optimizer'
    | '/_authenticated/performance'
    | '/_authenticated/portfolio'
    | '/_authenticated/positions'
    | '/_authenticated/readiness'
    | '/_authenticated/shadow'
    | '/_authenticated/signals'
    | '/_authenticated/strategies'
    | '/_authenticated/accounts/new'
    | '/_authenticated/backtests/$id'
    | '/_authenticated/accounts/$id/activate'
    | '/api/public/cron/autonomous'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicCronAutonomousRoute: typeof ApiPublicCronAutonomousRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shadow': {
      id: '/_authenticated/shadow'
      path: '/shadow'
      fullPath: '/shadow'
      preLoaderRoute: typeof AuthenticatedShadowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/readiness': {
      id: '/_authenticated/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof AuthenticatedReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optimizer': {
      id: '/_authenticated/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof AuthenticatedOptimizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile': {
      id: '/_authenticated/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AuthenticatedMobileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intel': {
      id: '/_authenticated/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof AuthenticatedIntelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capital': {
      id: '/_authenticated/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof AuthenticatedCapitalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autonomous': {
      id: '/_authenticated/autonomous'
      path: '/autonomous'
      fullPath: '/autonomous'
      preLoaderRoute: typeof AuthenticatedAutonomousRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/altdata': {
      id: '/_authenticated/altdata'
      path: '/altdata'
      fullPath: '/altdata'
      preLoaderRoute: typeof AuthenticatedAltdataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accuracy': {
      id: '/_authenticated/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AuthenticatedAccuracyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtests/$id': {
      id: '/_authenticated/backtests/$id'
      path: '/backtests/$id'
      fullPath: '/backtests/$id'
      preLoaderRoute: typeof AuthenticatedBacktestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/new': {
      id: '/_authenticated/accounts/new'
      path: '/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AuthenticatedAccountsNewRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
    '/api/public/cron/autonomous': {
      id: '/api/public/cron/autonomous'
      path: '/api/public/cron/autonomous'
      fullPath: '/api/public/cron/autonomous'
      preLoaderRoute: typeof ApiPublicCronAutonomousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts/$id/activate': {
      id: '/_authenticated/accounts/$id/activate'
      path: '/$id/activate'
      fullPath: '/accounts/$id/activate'
      preLoaderRoute: typeof AuthenticatedAccountsIdActivateRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
  }
}

interface AuthenticatedAccountsRouteChildren {
  AuthenticatedAccountsNewRoute: typeof AuthenticatedAccountsNewRoute
  AuthenticatedAccountsIdActivateRoute: typeof AuthenticatedAccountsIdActivateRoute
}

const AuthenticatedAccountsRouteChildren: AuthenticatedAccountsRouteChildren = {
  AuthenticatedAccountsNewRoute: AuthenticatedAccountsNewRoute,
  AuthenticatedAccountsIdActivateRoute: AuthenticatedAccountsIdActivateRoute,
}

const AuthenticatedAccountsRouteWithChildren =
  AuthenticatedAccountsRoute._addFileChildren(
    AuthenticatedAccountsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRouteWithChildren
  AuthenticatedAccuracyRoute: typeof AuthenticatedAccuracyRoute
  AuthenticatedAltdataRoute: typeof AuthenticatedAltdataRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedAutonomousRoute: typeof AuthenticatedAutonomousRoute
  AuthenticatedCapitalRoute: typeof AuthenticatedCapitalRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedIntelRoute: typeof AuthenticatedIntelRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedMobileRoute: typeof AuthenticatedMobileRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOptimizerRoute: typeof AuthenticatedOptimizerRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedReadinessRoute: typeof AuthenticatedReadinessRoute
  AuthenticatedShadowRoute: typeof AuthenticatedShadowRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
  AuthenticatedBacktestsIdRoute: typeof AuthenticatedBacktestsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRouteWithChildren,
  AuthenticatedAccuracyRoute: AuthenticatedAccuracyRoute,
  AuthenticatedAltdataRoute: AuthenticatedAltdataRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedAutonomousRoute: AuthenticatedAutonomousRoute,
  AuthenticatedCapitalRoute: AuthenticatedCapitalRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedIntelRoute: AuthenticatedIntelRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedMobileRoute: AuthenticatedMobileRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOptimizerRoute: AuthenticatedOptimizerRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedReadinessRoute: AuthenticatedReadinessRoute,
  AuthenticatedShadowRoute: AuthenticatedShadowRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
  AuthenticatedBacktestsIdRoute: AuthenticatedBacktestsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicCronAutonomousRoute: ApiPublicCronAutonomousRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
