/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedAccountsNewRouteImport } from './routes/_authenticated/accounts.new'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsNewRoute =
  AuthenticatedAccountsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/accounts/new': typeof AuthenticatedAccountsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/accounts/new': typeof AuthenticatedAccountsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/accounts'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/dashboard'
    | '/history'
    | '/positions'
    | '/signals'
    | '/accounts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/accounts'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/dashboard'
    | '/history'
    | '/positions'
    | '/signals'
    | '/accounts/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/accounts'
    | '/_authenticated/analytics'
    | '/_authenticated/approvals'
    | '/_authenticated/automation'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/positions'
    | '/_authenticated/signals'
    | '/_authenticated/accounts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/new': {
      id: '/_authenticated/accounts/new'
      path: '/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AuthenticatedAccountsNewRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
  }
}

interface AuthenticatedAccountsRouteChildren {
  AuthenticatedAccountsNewRoute: typeof AuthenticatedAccountsNewRoute
}

const AuthenticatedAccountsRouteChildren: AuthenticatedAccountsRouteChildren = {
  AuthenticatedAccountsNewRoute: AuthenticatedAccountsNewRoute,
}

const AuthenticatedAccountsRouteWithChildren =
  AuthenticatedAccountsRoute._addFileChildren(
    AuthenticatedAccountsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
